#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>
#include <string>
#include <math.h>
#include <cstdlib>
#include <vector>
#include <unordered_map>
#include <cassert>
#include <filesystem>
#include <memory>
#include <functional>
#include <unordered_map>
#include <iostream>//only used for debugging can be removed
#include <stdexcept>
#include <fstream>
#include <random>
#include "EntityFactory.hpp"
#include "map.hpp"
#include "CutScene.hpp"
#include "Animation.hpp"
#include "CollisionDetector.hpp"
#include "TextBox.hpp"
#include "Entity.hpp"
#include "idk.hpp"
#include "attack.hpp"
#include "Boss.hpp"
#include "PacMan.hpp"
#include "player.hpp"
#include "npc.hpp"
#include "Menu.hpp"
#include "GameOverScreen.hpp"
#include "item.hpp"
#include "inventory.hpp"